server:
  port: 8888
spring:
  application:
    admin: mgr

  #关闭默认模板引擎
  thymeleaf:
    cache: false
    enabled: false
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  messages:
    always-use-message-format: false
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
  # Oracle settings
  dataSource:
    mgr:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.6.8:1521:gnnt
      username: trade_forward
      password: password
    business:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.6.8:1521:gnnt
      username: trade_p2c_new
      password: password
    # HikariCP settings
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5


