spring:
  rabbitmq:
    addresses: 192.168.88.129
    port: 5672
    username: test
    password: test
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 10000
          max-interval: 1200000
          multiplier: 1

mzw:
  rabbitmq:
    ttl:
      queue: ttl_queue
      message: 10000
      exchange: ttl_exchange
      routing:
        key: ttl_routing_key
    normal:
      queue: normal_queue
      exchange: normal_exchange
      routing:
        key: normal_routing_key
